export const plans = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    period: "Forever",
    description: "Perfect for getting started.",
    button: "Get Started",
    featured: false,
    features: [
      "SAT Guide",
      "Blog Articles",
      "Free Practice Questions",
      "20 AI Messages / Day",
      "Preview Lessons",
      "Selected Mock Tests",
      "Basic Progress Tracking",
    ],
  },
  {
    id: "premium_monthly",
    name: "Premium Monthly",
    price: "$XX",
    period: "/month",
    description: "Flexible monthly subscription.",
    button: "Subscribe Monthly",
    featured: true,
    badge: "Most Popular",
    features: [
      "Unlimited AI SAT Tutor",
      "Complete SAT Courses, Including Video Lessons",
      "Access to All Mock Tests",
      "Advanced Analytics (Coming Soon)",
      "Priority Access to New Features",
    ],
  },
  {
    id: "premium_yearly",
    name: "Premium Yearly",
    price: "$XXX",
    period: "/year",
    description: "Best value for serious students.",
    button: "Subscribe Yearly",
    featured: false,
    badge: "Best Value",
    features: [
      "Everything in Premium Monthly",
      "2 Months Free vs. Monthly Billing",
      "Unlimited AI SAT Tutor",
      "Complete SAT Courses, Including Video Lessons",
      "Access to All Mock Tests",
      "Advanced Analytics (Coming Soon)",
      "Priority Access to New Features",
    ],
  },
];